spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mnm_db
    username: user1
    password: password123
  security:
    user:
      name: user
      password: password123