spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mnm_db
    username: user1
    password: password123
  security:
    user:
      name: user
      password: password123
    oauth2:
      client:
        registration:
          keycloak:
            client-id: movie-night-manager
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:28080/auth/realms/master