version: '3'
services:
  db:
    container_name: mnm-db
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mnm_db