version: '3'
services:
  postgresql:
    container_name: mnm-db
    image: docker.io/bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mnm_db